---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
    app: app
  namespace: peter
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    testing: testing
